apiVersion: v1
kind: Service
metadata:
  name: apache2
  labels:
    app: apache2
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31180
  selector:
    app: apache2
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: apache2
  labels:
    app: apache2
spec:
  selector:
    matchLabels:
      app: apache2
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache2
        tier: frontend
    spec:
      containers:
      - image: httpd:2.4
        name: apache2
        ports:
        - containerPort: 80
          name: apache2
        volumeMounts:
        - name: sysdig-scap-storage
          mountPath: /usr/local/apache2/htdocs/
          subPath: sysdig
      volumes:
      - name: sysdig-scap-storage
        # hostPath:
        #   path: /sysdig
        flexVolume:
         driver: ceph.rook.io/rook
         fsType: ceph
         options:
           fsName: myfs-ec
           clusterNamespace: rook-ceph
           path: /
