apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ceph.rook.io/block
  finalizers:
  - kubernetes.io/pv-protection
  name: sysdig-scap-storage-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    name: sysdig-scap-storage-pvc2
  flexVolume:
    driver: ceph.rook.io/rook-ceph-system
    fsType: xfs
    options:
      clusterNamespace: rook-ceph
      dataPool: ec-data-pool
      pool: replicated-metadata-pool
      storageClass: rook-ceph-block
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rook-ceph-block
