############################ DEPRECATION NOTICE ##########################
# This daemonset yaml configures everything as an environment variable.
# We recommend to use v2 daemonset which instead leverages Kubernetes
# best practices like Secrets and ConfigMaps
##########################################################################
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sysdig
  labels:
    app: sysdig
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sysdig
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: sysdig-scap-storage
        # hostPath:
        #   path: /var/sysdig
        persistentVolumeClaim:
          claimName: sysdig-scap-storage-pvc2
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: dev-vol
        hostPath:
          path: /dev
      - name: proc-vol
        hostPath:
          path: /proc
      - name: boot-vol
        hostPath:
          path: /boot
      - name: modules-vol
        hostPath:
          path: /lib/modules
      - name: usr-vol
        hostPath:
          path: /usr
      hostNetwork: false
      hostPID: true
      hostIPC: true
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      ### OPTIONAL: If using OpenShift or Kubernetes RBAC you need to uncomment the following line
      # serviceAccount: sysdig
      terminationGracePeriodSeconds: 5
      containers:
      - name: sysdig
        image: sysdig/sysdig
        # image: monitoringartist/dockbix-agent-xxl-limited
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          # Resources needed are subjective on the actual workload
          # please refer to Sysdig Support for more info about it
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1024Mi
        # readinessProbe:
        #   exec:
        #     command: [ "sysdig", "-G", "60", "-W", "5","-z", "-w", "/var/sysdig/$(MY_NODE_NAME)-$(date +%Y%m%d-%H%M%S).scap" ]
          # initialDelaySeconds: 10
        # command: [ "sysdig", "-G", "60", "-W", "5","-z", "-w", "/var/sysdig/$(MY_NODE_NAME)-%Y%m%d-%H%M%S.scap" ]
        command: [ "sh", "-c"]
        args:
        - mkdir /var/sysdig/$(MY_NODE_NAME) ; sysdig -G 300 -W 5 -z -w /var/sysdig/$(MY_NODE_NAME)/$(MY_NODE_NAME)-$(date +%Y%m%d-%H%M%S).scap;
        # - printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE;
        # - while true; do
        #     echo -en '\n';
        #     echo "hii- $(date +%Y%m%d-%H%M%S)" >> /var/sysdig/$(MY_NODE_NAME)-$(date +%Y%m%d-%H%M%S).txt;
        #     printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE;
        #     printenv MY_POD_IP MY_POD_SERVICE_ACCOUNT;
        #     sleep 10;
        #   done;
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName

        volumeMounts:
        - name: sysdig-scap-storage
          mountPath: /var/sysdig
          subPath: sysdig
        - mountPath: /host/var/run/docker.sock
          name: docker-sock
          readOnly: false
        - mountPath: /host/dev
          name: dev-vol
          readOnly: false
        - mountPath: /host/proc
          name: proc-vol
          readOnly: true
        - mountPath: /host/boot
          name: boot-vol
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules-vol
          readOnly: true
        - mountPath: /host/usr
          name: usr-vol
          readOnly: true
        - mountPath: /dev/shm
          name: dshm
