    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: nfs-storage
    spec:
      storageClassName: "rook-ceph-block"
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 6Gi
